### ISSUE TITLE
Can‘t use in Safari 13 (macOS Mojave and Catalina)

### ISSUE THREAD

**Issue by mrdragonma** [televator-apps/vimari#136]
### Version

- [ ] Version 1
- [ ] Version 2

### My Problem
Can‘t use in Safari 13(macOS catalina)

**Comment by nchase** [comment]
@mrdragonma can you provide any more details?

Did you try building it using the Safari 12 steps? Any error messages or stack traces?

**Comment by danielcompton** [comment]
Btw, I'm working on a build for Safari 13 + Catalina to help solve this.

**Comment by mrdragonma** [comment]
> @mrdragonma can you provide any more details?
> 
> Did you try building it using the Safari 12 steps? Any error messages or stack traces?

I build it using Safari 12 steps. When the empty box GUI appear,the Safari's extensions don't have vimari. As far as I know, the extension policy has changed in Safari 13 for security. You can notice it.

**Comment by mrdragonma** [comment]
@nchase 
I build it using Safari 12 steps. When the empty box GUI appear,the Safari's extensions don't have vimari. As far as I know, the extension policy has changed in Safari 13 for security. You can notice it.

**Comment by shaunpatel** [comment]
Any updates for Safari 13? Thanks!

**Comment by danielcompton** [comment]
Follow along with https://github.com/televator-apps/vimari/issues/139. The app is currently waiting for review.

**Comment by danielcompton** [comment]
@mrdragonma can you try https://github.com/televator-apps/vimari/releases/tag/v2.0.2 and let me know if that version works for you?

**Comment by ingjieye** [comment]
> @mrdragonma can you try https://github.com/televator-apps/vimari/releases/tag/v2.0.2 and let me know if that version works for you?

I'm using Safari 13.0 (14608.1.49) with macOS 10.14.6 (18G95) .

Navigation between tabs and closing tabs not working. Others seems working great.

**Comment by jdf221** [comment]
> Navigation between tabs and closing tabs not working.

That's because the tab navigation and tab closing is still using the old Safari extension functions. (Which no longer exist/work)

Example: https://github.com/televator-apps/vimari/blob/c9dfd59cd0d5305ef7d9e0f73ec11b7648ef7aff/Vimari%20Extension/js/injected.js#L39-L40

`safari.self.tab.dispatchMessage` no longer exists. With Safari's new extension model you have to dispatch the message to the extension's Swift/app context and handle it there.

And to make matters more fun the new extension model doesn't support changing and closing tabs. (Unless things have changed since I last looked)

If there is no better way to do tabs I posted a way to do it in an old issue: https://github.com/televator-apps/vimari/issues/103#issuecomment-414159407 (2nd part)

Also @danielcompton https://github.com/televator-apps/vimari/blob/master/Vimari%20Extension/js/global.js isn't used at all as far as I can tell. Not sure if you're keeping it around for a reason, pretty much all of it is using the old extension API.

**Comment by danielcompton** [comment]
> And to make matters more fun the new extension model doesn't support changing and closing tabs. (Unless things have changed since I last looked)

Thankfully they have changed, though I'm not sure in which version of SafariServices, which makes feature detection tricky. I've pushed 1b787b5649bcbb7355805428e220917c5dc67fd5 which implements changing tabs. I'll do closing tabs in a little bit.

> Not sure if you're keeping it around for a reason, pretty much all of it is using the old extension API.

Mostly just for reference while I translate things over. I'll remove it once everything is implemented in the new model.

**Comment by danielcompton** [comment]
I think this is resolved now.
