### ISSUE TITLE
Add custom keybinding settings

### ISSUE THREAD

**Issue by danielcompton** [televator-apps/vimari#142]
Currently all of the keybindings are hard-coded. It would be good to allow users to override keybindings with custom preferences. 

https://github.com/televator-apps/vimari/issues/103#issuecomment-414159407 has a little bit of detail on this, and the app currently has some saving/loading of preferences but none of it is exposed to the end-user.

**Comment by michael-yx-wu** [comment]
This is a sorely missed feature. Sites like Github (e.g. binds `t` to file explorer, conflicts with new tab action) and Youtube (see #148) tend to conflict with some of the hardcoded Vimari keybindings. In addition to custom keybindings, it would be lovely to bring back the whitelist/blacklist.

I guess quite a bit is different due to Apple's newly-mandated extension changes, but I hope these are still possible to implement :)

**Comment by eproxus** [comment]
It's also a bit weird that a web page can override the Vimari keybindings. On GitHub <kbd>t</kbd> doesn't create a new tab but triggers GitHubs file explorer instead. Other Vim extensions seem to have an input mode bound to <kbd>i</kbd> which let's the user send input to the web page, but Vimary lacks this?

**Comment by ssh352** [comment]
w and q to navigate tabs is bit weird. It would be nice to allow customization.

**Comment by Benjamin-Lee** [comment]
Moreover, I'd actually like to disable some of the keybindings since I never use them and only unintentionally hit them.
