### ISSUE TITLE
The 2.0.3 version info has not been updated to be displayed in Safari

### ISSUE THREAD

**Issue by orthodoX** [televator-apps/vimari#145]
### Version

- [ ] Version 1
- [x ] Version 2

### My Problem
I know this is a minor one, but still it is misleading. The 2.0.3 version info has not been updated to be properly displayed in the Safari's extensions tab. It's still displaying the 2.0.2

<img width="475" alt="Screenshot 2019-09-26 at 00 00 00" src="https://user-images.githubusercontent.com/370935/65643052-01186880-dff1-11e9-99ac-80381f1baabb.png">

**Comment by danielcompton** [comment]
Thanks for reporting this. I'm pretty sure I updated the Safari extension version too here: https://github.com/televator-apps/vimari/commit/8122fd5b3470222c11e34e61f96a3ac52efd66f8. 

A few troubleshooting questions:

* What file path shows up when you click the Uninstall button? I'm wondering whether Safari is picking up the 2.0.2 version somewhere instead of the 2.0.3 version you've downloaded.
* Can you try restarting Safari and see if the version changes?

In general, I find the Safari extension mechanism very buggy for updating versions, and often have to restart Safari when developing to make things work properly.

**Comment by orthodoX** [comment]
Yep, restarting Safari, updated the version number correctly. 👍 
Closing this one.
