### ISSUE TITLE
Where is the configuration file or how to configure vimari?

### ISSUE THREAD

**Issue by yanzhang0219** [televator-apps/vimari#166]
macOS version: 10.15.3
vamri: App Store

I want to customize the keybindings but I cannot find the configuration file, and also, I the vamri window, there is no such a button like "open configuration file". I remembered this existed before.
Thanks a lot!

**Comment by beyondcompute** [comment]
Yeah, the same issue here (sorry for the not-so-informative comment). Same version of macOS, Safari 13.0.5. No ability to access settings. And configuring a prefix would have been great because `f` does not work when focus is in a text field.

**Comment by sooheon** [comment]
This would also allow for putting blacklists for sites that provide their own vi-ish keys (GitHub included).

**Comment by xueguangl23** [comment]
Same issue, the ability to configure is crucial.

**Comment by gaisin** [comment]
Same here, I was looking for a way to set Command Prefix, because on many websites keys already bonded for inner commands. But I couldn't any settings in extension's page.

I've also tried to install Vimari v1.13 manually, but couldn't make this setting work for Control button. Tried to type "Control", "control", "Ctrl", "ctrl", but nothing worked.

**Comment by eudinaesis** [comment]
It looks like the config file is here: https://github.com/televator-apps/vimari/blob/master/Vimari%20Extension/js/settings.js -- but it would really help if there were instructions for how to build the app from the source (if that's even doable without an Apple developer ID, etc). And if it's not doable by normal people, then yes, please, it would be very very helpful to have a config option in the built app.

... thanks for making this, though! I've been missing this so much since Safari 13!

**Comment by kerrybassett** [comment]
Here is a workaround that worked for me.  I found the settings.js file in the install location of the application on my machine(/Applications/Vimari.app/Contents/PlugIns/Vimari Extension.appex/Contents/Resources for me).  In there I found the settings.js file and was able to edit the settings.  Once I reloaded the extension my new settings were applied.

**Comment by danseely** [comment]
I'll add that, as it stands, the README is fairly misleading in that it references these settings, and there's no mention of how to get to them, or that you _can't_ currently get to them. I'd appreciate a little clarity in the README about the current status.

**Comment by minego** [comment]
Has anyone managed to build this, and if so can you please provide some steps?

I have successfully built it, by setting it to sign locally, but safari won't show the extension in its list, so I can't change it. All I want is to be able to change some keybindings. This shouldn't be this difficult.

**Comment by nbelzer** [comment]
I'm closing this issue as the requested configuration option is now available in the master branch. When running this version you'll be able to open the configuration file through the Vimari.app, see screenshot below.

<img width="500" alt="Screenshot 2020-07-25 at 12 48 24" src="https://user-images.githubusercontent.com/7622933/88455390-368e1c80-ce75-11ea-8816-90bc945f622f.png">

**Comment by danseely** [comment]
Great news, this is a huge advancement of the project! Any idea on a timeline for App Store update?

**Comment by yanzhang0219** [comment]
Wow, thank you!!! The last update in App Store is 9 months ago, so could you please update it soon?

**Comment by nbelzer** [comment]
Hey there, nice to hear people are enthusiastic about this. I am working on the project in my spare time (mostly during the weekends) and need a little more time for some final additions before making up the release.

**Comment by danseely** [comment]
No worries at all. Thanks a ton for making Vimari!
