### ISSUE TITLE
Is it possible to define multiple bindings for same action

### ISSUE THREAD

**Issue by nikitavoloboev** [televator-apps/vimari#187]
For example I'd like to trigger `goToPageTop` with `shift+k` and also `g g`.

**Comment by nbelzer** [comment]
The solution in #78 was not sufficient to work with the current day Vimari (the PR was open since 2016) as it missed support for modifiers. I've included some work in the branch `187-multiple-shortcut-support` that does support modifiers. I will open a PR for this once #194 has been merged as it builds upon that work.
