### ISSUE TITLE
Make keys not bound to anything in normal mode be usable

### ISSUE THREAD

**Issue by nikitavoloboev** [televator-apps/vimari#188]
If I haven't bound a key to anything, it should be available for use as if you are in insert mode.

For example arrow keys in YouTube should work as I haven't bound arrow keys to anything in my bindings:

```
"bindings": {
      "hintToggle": "f",
      "newTabHintToggle": "shift+f",
      "scrollUp": "k",
      "scrollDown": "j",
      "scrollLeft": "h",
      "scrollRight": "l",
      "goToPageTop": "g g",
      "goToPageBottom": "shift+g",
      "goToFirstInput": ":",
      "goBack": "shift+j",
      "goForward": "shift+k",
      "reload": "r",
      "tabBack": "a",
      "tabForward": "w",
      "closeTab": "e",
  }
```

Same for all other keys. Like `v` or `o` and so on. This was allowed by [sVim](https://github.com/flippidippi/sVim) too and is super useful.

**Comment by danielcompton** [comment]
Yeah, I've noticed this too and I think it's a pretty big workflow regression. We should fix this or revert the normal mode patch before submitting to the App Store.

**Comment by nbelzer** [comment]
I've implemented this behaviour in branch `188-normal-mode-non-bound-keys`. As we can only isolate keys on a per-key-basis I had to isolate all keys that are bound according to the settings. This means that even though by default <kbd>g</kbd> doesn't do anything in Vimari it is isolated because it is part of both <kbd>g</kbd>+<kbd>i</kbd>,<kbd>shift</kbd>+<kbd>g</kbd>, and <kbd>g</kbd>+<kbd>g</kbd>. See included code below for reference.

In my opinion we should add this as a preference (something like `transparentBindings`) that defaults to true as it is a workflow regression as said before.


```js
// Returns all keys bound in the settings.
function boundKeys() {
    var bindings = Object.values(settings.bindings)
        // Split multi-key bindings.
        .flatMap(s => s.split("+"))
    bindings.push(settings.modifier)
    // Use a set to remove duplicates.
    return new Set(bindings)
}
```

**Comment by xster** [comment]
Random note for future readers: if you made your userSettings.json before #194, missing json keys don't seem to inherit from the default settings. You have to specifically add it to your userSettings.json it seems.
