### ISSUE TITLE
Not Working When On Search Engines (e.g. Google, DuckDuckGo)

### ISSUE THREAD

**Issue by pyrmont** [televator-apps/vimari#250]
**Describe the bug**
The keyboard shortcuts do not work on the search results page of certain search engines (notably Google and DuckDuckGo).

**To Reproduce**
1. Go to [duckduckgo.com](https://duckduckgo.com).
2. Type 'vimari' into the search box.
3. Press RETURN.
4. Press `j`.

**Expected behaviour**
The page scrolls.

**Actual behaviour**
The page does not scroll.

**Desktop (please complete the following information):**

- macOS version: 11.6
- Safari version: 15.0
- Vimari version: 2.1.1

**Additional context**
* The keyboard shortcuts _will work_ if you click with the mouse somewhere in the results page. If I had to guess, I'd assume that Google and DuckDuckGo are attempting to do some kind of keyboard hijacking so that things that you type will appear in the search field. Presumably, when you click outside the search box, that interrupts this hijacking and returns things to normal.
* If you reload a results page (⌘R), the keyboard shortcuts do work. 
* This is a possible duplicate of #38 and #228.

**Comment by mstoops** [comment]
Out of curiosity, what is the specific build of Safari you're using. I've got the latest update (Version 15.0 (16612.1.29.41.4, 16612)), and Vimari has stopped working completely. I'm planning on putting a bug report in, unless for some reason it's specific to my machine.

**Comment by pyrmont** [comment]
My build is the same: Safari 15.0 (16612.1.29.41.4, 16612).

**Comment by mstoops** [comment]
> My build is the same: Safari 15.0 (16612.1.29.41.4, 16612).

(Turns out I had an invalid URL pattern in my excludedURL, which is strange as I hadn't touched it in a long time, and I could have sworn it was working at one point. Wouldn't have found it out except for having the Console open in the Inspector, when the plugin loaded.)

In regards to your filed issue, I followed your directions exactly, and it worked as expected; I went to duckduckgo.com, typed _vimari_ in the search box, hit _Return_, and the "j" scrolled as it should have _without_ having to click anywhere on the results page 1st. This worked properly with Google as well. You might try opening the Console in the Inspector to see if you get any errors. I am, btw, running the exact same environment as you macOS 11.6/Safari 15.0/Vimari 2.1.1).

**Comment by pyrmont** [comment]
@mstoops Thanks for checking. The problem must be caused by something I'm running locally. I run 1Blocker but I see the same problem even when I disable it. I also run Karabiner but, again, turning it off didn't make a difference. In the Console, I see the error `Unrecognized Content-Security-Policy directive 'worker-src'` but that [looks like](https://stackoverflow.com/a/67163499/308909) something that would be common to every instance of Safari.

I'll close the issue for now since I don't think this is a problem with Vimari. I realised looking around that DuckDuckGo has its own supported keyboard shortcuts and I have the same problem with those so it must be a problem with my setup.
